const { DatabaseSync } = require('node:sqlite');
const fs = require('fs');
const path = require('path');
const bcrypt = require('bcryptjs');
const dataDirectory = path.join(__dirname, '../data');
fs.mkdirSync(dataDirectory, { recursive: true });
// Node 24 includes SQLite, so this project does not depend on a native addon.
// That keeps setup reliable on Windows machines where install scripts are blocked.
const db = new DatabaseSync(path.join(dataDirectory, 'aurum-sim.db'));
function initializeDatabase() { db.exec(`CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY, name TEXT NOT NULL, email TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL); CREATE TABLE IF NOT EXISTS admin_users (id INTEGER PRIMARY KEY, name TEXT NOT NULL, email TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL); CREATE TABLE IF NOT EXISTS accounts (id INTEGER PRIMARY KEY, user_id INTEGER NOT NULL, name TEXT NOT NULL, account_type TEXT NOT NULL, account_number TEXT UNIQUE NOT NULL, balance REAL NOT NULL, available_balance REAL NOT NULL, status TEXT NOT NULL DEFAULT 'ACTIVE', transfers_enabled INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP); CREATE TABLE IF NOT EXISTS transactions (id INTEGER PRIMARY KEY, user_id INTEGER NOT NULL, account_id INTEGER NOT NULL, reference TEXT UNIQUE NOT NULL, recipient_name TEXT, recipient_account TEXT, recipient_bank TEXT, amount REAL NOT NULL, description TEXT, status TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP); CREATE TABLE IF NOT EXISTS notifications (id INTEGER PRIMARY KEY, user_id INTEGER NOT NULL, title TEXT NOT NULL, body TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP); CREATE TABLE IF NOT EXISTS system_settings (setting_key TEXT PRIMARY KEY, setting_value TEXT NOT NULL); CREATE TABLE IF NOT EXISTS audit_logs (id INTEGER PRIMARY KEY, admin_id INTEGER, action TEXT NOT NULL, detail TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP); CREATE TABLE IF NOT EXISTS app_metadata (meta_key TEXT PRIMARY KEY, meta_value TEXT NOT NULL);`); }
function seedDatabase() { if (db.prepare('SELECT COUNT(*) AS count FROM users').get().count) return; const user = db.prepare('INSERT INTO users (name,email,password_hash) VALUES (?,?,?)').run('Amara Okafor','amara@aurumsim.test',bcrypt.hashSync('demo1234', 12)); db.prepare('INSERT INTO admin_users (name,email,password_hash) VALUES (?,?,?)').run('Aurum Administrator','admin@aurumsim.test',bcrypt.hashSync('admin1234', 12)); const create = db.prepare('INSERT INTO accounts (user_id,name,account_type,account_number,balance,available_balance) VALUES (?,?,?,?,?,?)'); create.run(user.lastInsertRowid,'Everyday Account','CURRENT','2098746310',8500,8500); create.run(user.lastInsertRowid,'Growth Savings','SAVINGS','2098746311',24000,24000); create.run(user.lastInsertRowid,'Studio Business','BUSINESS','2098746312',57000,57000); db.prepare('INSERT INTO transactions (user_id,account_id,reference,recipient_name,recipient_account,recipient_bank,amount,description,status) VALUES (?,?,?,?,?,?,?,?,?)').run(user.lastInsertRowid,1,'AUR-START01','Nova Studio','0112345678','Aurum Sim',1250,'Design retainer','COMPLETED'); db.prepare('INSERT INTO notifications (user_id,title,body) VALUES (?,?,?)').run(user.lastInsertRowid,'Welcome to Aurum','Your account overview is ready.'); db.prepare('INSERT INTO system_settings VALUES (?,?)').run('transfers_enabled','true'); db.prepare('INSERT INTO system_settings VALUES (?,?)').run('default_transaction_result','COMPLETED'); }
function migrateToUsd() { if (db.prepare("SELECT 1 FROM app_metadata WHERE meta_key = 'usd_migration_v1'").get()) return; db.exec('UPDATE accounts SET balance = balance / 100, available_balance = available_balance / 100; UPDATE transactions SET amount = amount / 100;'); db.prepare('INSERT INTO app_metadata (meta_key, meta_value) VALUES (?, ?)').run('usd_migration_v1', new Date().toISOString()); }
module.exports = { db, initializeDatabase, seedDatabase, migrateToUsd };
