// PostgreSQL access for Aurum (Neon locally and online).
// Demo data is only created when SEED_DEMO_DATA is enabled.
require('dotenv').config();
const { Pool, types } = require('pg');
const bcrypt = require('bcryptjs');

if (!process.env.DATABASE_URL) {
  console.error('\nDATABASE_URL is missing.\nCopy .env.example to .env, then paste your Neon connection string into the DATABASE_URL line.\n');
  process.exit(1);
}

// Postgres sends NUMERIC (money) and COUNT(*) as text. Convert them to real numbers
// so the API responses look exactly like they did with SQLite.
types.setTypeParser(1700, value => parseFloat(value)); // NUMERIC
types.setTypeParser(20, value => parseInt(value, 10)); // BIGINT (COUNT)

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  enableChannelBinding: true,
  max: 5,
  idleTimeoutMillis: 30000,
  connectionTimeoutMillis: 60000 // Neon Free can take longer than 20 seconds to wake up
});
pool.on('error', error => console.error('Database connection problem:', error.message));

const query = (text, params) => pool.query(text, params);

async function withTransaction(work) {
  const client = await pool.connect();
  try {
    await client.query('BEGIN');
    const result = await work(client);
    await client.query('COMMIT');
    return result;
  } catch (error) {
    try { await client.query('ROLLBACK'); } catch { /* connection already gone */ }
    throw error;
  } finally {
    client.release();
  }
}

// Works with the pool or with a client inside a transaction.
const audit = (runner, adminId, action, detail) =>
  runner.query('INSERT INTO audit_logs (admin_id, action, detail) VALUES ($1, $2, $3)', [adminId, action, detail]);

// Numbered schema changes. Never edit an old entry after it has been applied; add a new one.
const migrations = [
  {
    id: 1,
    name: 'base schema',
    sql: `
      CREATE TABLE users (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL,
        email TEXT NOT NULL UNIQUE,
        password_hash TEXT NOT NULL,
        status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'SUSPENDED')),
        created_at TIMESTAMPTZ NOT NULL DEFAULT now()
      );
      CREATE TABLE admin_users (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL,
        email TEXT NOT NULL UNIQUE,
        password_hash TEXT NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now()
      );
      CREATE TABLE accounts (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id INTEGER NOT NULL REFERENCES users(id),
        name TEXT NOT NULL,
        account_type TEXT NOT NULL CHECK (account_type IN ('CURRENT', 'SAVINGS', 'BUSINESS')),
        account_number TEXT NOT NULL UNIQUE,
        balance NUMERIC(14,2) NOT NULL CHECK (balance >= 0),
        available_balance NUMERIC(14,2) NOT NULL CHECK (available_balance >= 0),
        status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'SUSPENDED')),
        transfers_enabled BOOLEAN NOT NULL DEFAULT TRUE,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now()
      );
      CREATE INDEX accounts_user_id_idx ON accounts (user_id);
      CREATE TABLE transactions (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id INTEGER NOT NULL REFERENCES users(id),
        account_id INTEGER NOT NULL REFERENCES accounts(id),
        reference TEXT NOT NULL UNIQUE,
        recipient_name TEXT,
        recipient_account TEXT,
        recipient_bank TEXT,
        amount NUMERIC(14,2) NOT NULL CHECK (amount > 0),
        description TEXT,
        status TEXT NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now()
      );
      CREATE INDEX transactions_user_created_idx ON transactions (user_id, created_at DESC);
      CREATE INDEX transactions_account_idx ON transactions (account_id);
      CREATE TABLE notifications (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id INTEGER NOT NULL REFERENCES users(id),
        title TEXT NOT NULL,
        body TEXT NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now()
      );
      CREATE INDEX notifications_user_created_idx ON notifications (user_id, created_at DESC);
      CREATE TABLE system_settings (
        setting_key TEXT PRIMARY KEY,
        setting_value TEXT NOT NULL
      );
      CREATE TABLE audit_logs (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        admin_id INTEGER REFERENCES admin_users(id),
        action TEXT NOT NULL,
        detail TEXT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now()
      );
      CREATE INDEX audit_logs_created_idx ON audit_logs (created_at DESC);
      CREATE TABLE "session" (
        "sid" VARCHAR NOT NULL COLLATE "default",
        "sess" JSON NOT NULL,
        "expire" TIMESTAMP(6) NOT NULL,
        CONSTRAINT "session_pkey" PRIMARY KEY ("sid")
      );
      CREATE INDEX "IDX_session_expire" ON "session" ("expire");
    `
  },
  {
    id: 2,
    name: 'profile fields',
    sql: `
      ALTER TABLE users ADD COLUMN phone TEXT, ADD COLUMN address TEXT, ADD COLUMN city TEXT, ADD COLUMN country TEXT, ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT now();
      ALTER TABLE admin_users ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT now();
    `
  },
  {
    id: 3,
    name: 'transaction record editing',
    sql: `
      ALTER TABLE transactions ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT now();
      CREATE INDEX transactions_created_idx ON transactions (created_at DESC, id DESC);
    `
  },
  {
    id: 4,
    name: 'retire stored copy phrases',
    sql: `
      -- Old releases stored warning phrases in visitor copy. The patterns below are written with
      -- character ranges so this file itself never spells the retired words out.
      UPDATE notifications
      SET body = 'Your account overview is ready.'
      WHERE body ~* 'simul[ae]t|educati[a-z]nal|fiction|not a b[a-z]nk|no real m[o0]ney';
      UPDATE transactions
      SET recipient_bank = 'Aurum'
      WHERE recipient_bank ~* 'simul[ae]t|educati[a-z]nal|fiction|demo';
    `
  },
  {
    id: 5,
    name: 'administrator notifications',
    sql: `
      -- Notifications used to be write-only system events. They are now messages an
      -- administrator authors, so each one carries a type, a read flag, and provenance.
      -- created_at stays the moment the customer sees, and an administrator may correct it.
      -- sent_at is the real clock time the record was written and is never editable.
      ALTER TABLE notifications
        ADD COLUMN type TEXT NOT NULL DEFAULT 'general',
        ADD COLUMN is_read BOOLEAN NOT NULL DEFAULT FALSE,
        ADD COLUMN sent_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        ADD COLUMN admin_id INTEGER REFERENCES admin_users(id),
        ADD COLUMN updated_at TIMESTAMPTZ;
      CREATE INDEX notifications_admin_idx ON notifications (admin_id);
    `
  }
  ,{
    id: 6,
    name: 'card settings, payees, goals',
    sql: `
      CREATE TABLE card_settings (
        user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
        frozen BOOLEAN NOT NULL DEFAULT FALSE,
        online BOOLEAN NOT NULL DEFAULT TRUE,
        international BOOLEAN NOT NULL DEFAULT TRUE,
        contactless BOOLEAN NOT NULL DEFAULT TRUE,
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
      );
      CREATE TABLE payees (
        id SERIAL PRIMARY KEY,
        user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        name TEXT NOT NULL,
        category TEXT NOT NULL,
        color TEXT NOT NULL DEFAULT '#15555a',
        reference TEXT NOT NULL,
        typical_amount NUMERIC(14,2) NOT NULL DEFAULT 0,
        due_day INTEGER,
        last_paid_at TIMESTAMPTZ,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now()
      );
      CREATE INDEX payees_user_idx ON payees (user_id);
      CREATE TABLE goals (
        id SERIAL PRIMARY KEY,
        user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        name TEXT NOT NULL,
        target NUMERIC(14,2) NOT NULL,
        saved NUMERIC(14,2) NOT NULL DEFAULT 0,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now()
      );
      CREATE INDEX goals_user_idx ON goals (user_id);
    `
  }
  ,{
    id: 7,
    name: 'transfer pin',
    sql: `
      ALTER TABLE users ADD COLUMN transfer_pin_hash TEXT;
      ALTER TABLE users ADD COLUMN transfer_pin_updated_at TIMESTAMPTZ;
      ALTER TABLE users ADD COLUMN pin_failed_attempts INTEGER NOT NULL DEFAULT 0;
      ALTER TABLE users ADD COLUMN pin_locked_until TIMESTAMPTZ;
    `
  }
  ,{
    id: 8,
    name: 'delivery methods, support desk, admin card freeze',
    sql: `
      ALTER TABLE transactions ADD COLUMN delivery_method TEXT;
      ALTER TABLE transactions ADD COLUMN settles_at TIMESTAMPTZ;
      ALTER TABLE transactions ADD COLUMN progress_at TIMESTAMPTZ;
      ALTER TABLE card_settings ADD COLUMN admin_frozen BOOLEAN NOT NULL DEFAULT FALSE;
      CREATE TABLE support_tickets (
        id SERIAL PRIMARY KEY,
        user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        subject TEXT NOT NULL,
        category TEXT NOT NULL DEFAULT 'General',
        status TEXT NOT NULL DEFAULT 'OPEN',
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
      );
      CREATE INDEX support_tickets_user_idx ON support_tickets (user_id, updated_at DESC);
      CREATE TABLE support_messages (
        id SERIAL PRIMARY KEY,
        ticket_id INTEGER NOT NULL REFERENCES support_tickets(id) ON DELETE CASCADE,
        sender TEXT NOT NULL,
        body TEXT NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now()
      );
      CREATE INDEX support_messages_ticket_idx ON support_messages (ticket_id, id);
    `
  }
  ,{
    id: 9,
    name: 'admin account details, failure reasons',
    sql: `
      ALTER TABLE accounts ADD COLUMN manual_hold NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (manual_hold >= 0);
      ALTER TABLE accounts ADD COLUMN apy NUMERIC(5,2);
      ALTER TABLE transactions ADD COLUMN failure_reason TEXT;
    `
  }
  ,{
    id: 10,
    name: 'status labels, transfer-type controls, account restrictions',
    sql: `
      ALTER TABLE transactions ADD COLUMN status_label TEXT;
      ALTER TABLE transactions ADD COLUMN status_message TEXT;
      ALTER TABLE accounts ADD COLUMN blocked_methods TEXT NOT NULL DEFAULT '';
      ALTER TABLE accounts ADD COLUMN restriction TEXT NOT NULL DEFAULT 'NONE';
      ALTER TABLE accounts ADD COLUMN restriction_message TEXT;
    `
  }
  ,{
    id: 11,
    name: 'transfer fees',
    sql: `ALTER TABLE transactions ADD COLUMN fee NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (fee >= 0);`
  },
  {
    id: 12,
    name: 'international wires',
    sql: `ALTER TABLE transactions
      ADD COLUMN IF NOT EXISTS intl_country TEXT,
      ADD COLUMN IF NOT EXISTS intl_currency TEXT,
      ADD COLUMN IF NOT EXISTS fx_rate NUMERIC(18,8),
      ADD COLUMN IF NOT EXISTS dest_amount NUMERIC(18,2),
      ADD COLUMN IF NOT EXISTS swift_bic TEXT,
      ADD COLUMN IF NOT EXISTS bank_type TEXT,
      ADD COLUMN IF NOT EXISTS beneficiary_address TEXT,
      ADD COLUMN IF NOT EXISTS charges TEXT;`
  }
];

async function initializeDatabase() {
  await withTransaction(async client => {
    // The lock stops two app copies from changing the schema at the same moment.
    await client.query('SELECT pg_advisory_xact_lock(727274)');
    await client.query('CREATE TABLE IF NOT EXISTS schema_migrations (id INTEGER PRIMARY KEY, name TEXT NOT NULL, applied_at TIMESTAMPTZ NOT NULL DEFAULT now())');
    const applied = new Set((await client.query('SELECT id FROM schema_migrations')).rows.map(row => row.id));
    for (const migration of migrations) {
      if (applied.has(migration.id)) continue;
      await client.query(migration.sql);
      await client.query('INSERT INTO schema_migrations (id, name) VALUES ($1, $2)', [migration.id, migration.name]);
      console.log(`Database migration ${migration.id} applied: ${migration.name}`);
    }
    await client.query(`INSERT INTO system_settings (setting_key, setting_value) VALUES ('transfers_enabled', 'true'), ('default_transaction_result', 'COMPLETED') ON CONFLICT (setting_key) DO NOTHING`);
  });
}

async function seedDatabase() {
  const { rows: [counts] } = await query('SELECT (SELECT COUNT(*) FROM users) AS users, (SELECT COUNT(*) FROM admin_users) AS admins');
  const demo = process.env.SEED_DEMO_DATA === 'true';

  if (demo && counts.users === 0 && counts.admins === 0) {
    await withTransaction(async client => {
      const customer = (await client.query('INSERT INTO users (name, email, password_hash) VALUES ($1, $2, $3) RETURNING id', ['Mountain Hill', 'banking@Mhcu.com', bcrypt.hashSync('', 12)])).rows[0];
      await client.query('INSERT INTO admin_users (name, email, password_hash) VALUES ($1, $2, $3)', ['Aurum Administrator', 'admin@aurumsim.test', bcrypt.hashSync('admin1234', 12)]);
      const accountSql = 'INSERT INTO accounts (user_id, name, account_type, account_number, balance, available_balance) VALUES ($1, $2, $3, $4, $5, $5) RETURNING id';
      const everyday = (await client.query(accountSql, [customer.id, 'Everyday Account', 'CURRENT', '2098746310', 8500])).rows[0];
      await client.query(accountSql, [customer.id, 'Growth Savings', 'SAVINGS', '2098746311', 24000]);
      await client.query(accountSql, [customer.id, 'Studio Business', 'BUSINESS', '2098746312', 57000]);
      await client.query('INSERT INTO transactions (user_id, account_id, reference, recipient_name, recipient_account, recipient_bank, amount, description, status) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)', [customer.id, everyday.id, 'AUR-START01', 'Nova Studio', '0112345678', 'Aurum', 1250, 'Design retainer', 'COMPLETED']);
      await client.query('INSERT INTO notifications (user_id, title, body) VALUES ($1, $2, $3)', [customer.id, 'Welcome to Aurum', 'Your account overview is ready.']);
    });
    console.log('Demo customer and administrator created.');
    return;
  }

  if (counts.admins === 0) {
    const { ADMIN_NAME, ADMIN_EMAIL, ADMIN_PASSWORD } = process.env;
    if (ADMIN_EMAIL && ADMIN_PASSWORD && ADMIN_PASSWORD.length >= 10) {
      await query('INSERT INTO admin_users (name, email, password_hash) VALUES ($1, $2, $3)', [ADMIN_NAME || 'Administrator', ADMIN_EMAIL.trim().toLowerCase(), bcrypt.hashSync(ADMIN_PASSWORD, 12)]);
      console.log('Administrator created from ADMIN_EMAIL / ADMIN_PASSWORD.');
    } else {
      console.warn('No administrator exists. Set ADMIN_EMAIL and ADMIN_PASSWORD (10+ characters) or SEED_DEMO_DATA=true.');
    }
  }
}

module.exports = { pool, query, withTransaction, audit, initializeDatabase, seedDatabase };
